import React from 'react';
import Head from 'next/head';
import Layout from './layout/Layout';

const Dashboard = () => {
  return (
    <Layout>
      <Head>
        <title>Insi Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="min-h-screen font-sans h-full antialiased">
        <div className="w-full flex justify-left items-left">
          <div className="w-full p-6 h-fit">
            <div className="flex flex-wrap items-center justify-around mb-4">
              <h2 className="text-xl">Dashboard Placeholder</h2>
            </div>
            <div className="px-0 sm:px-3 flex flex-col md:flex-row gap-7">
              <div className="bg-white p-4 rounded shadow w-full md:w-1/2">
                Section A
              </div>
              <div className="bg-white p-4 rounded shadow w-full md:w-1/2">
                Section B
              </div>
            </div>
            <div className="px-0 sm:px-3 pt-6 flex flex-col md:flex-row gap-7 my-1.5">
              <div className="bg-white p-4 rounded shadow w-full md:w-1/2">
                Section C
              </div>
              <div className="bg-white p-4 rounded shadow w-full md:w-1/2">
                Section D
              </div>
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
};

export default Dashboard;
